slam_toolbox:
  ros__parameters:

    # === Plugin params ===
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # === ROS Parameters ===
    
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: /scan
    mode: mapping
    publish_pose: true
    pose_publish_rate: 30.0
    scan_queue_size: 50
    use_pose_topic': false
    pose_topic: /slam_toolbox/pose

    # === Timing / Performance ===
    transform_publish_period: 0.15    # ลดภาระ TF
    map_publish_period: 0.5
    odom_publish__rate: 50
    map_update_interval: 0.5          # update map ช้าลง
    transform_timeout: 0.5
    tf_buffer_duration: 120.0
    minimum_time_interval: 0.1        # เว้นช่วง scan
    throttle_scans: 1                  # รับทุก 2 scans
    stack_size_to_use: 40000000       # เพิ่ม stack memory
    use_sim_time: False
    # === Scan Ranges ===
    max_laser_range: 12.0
    min_laser_range: 0.1

    resolution: 0.05
    use_scan_matching: true
    do_loop_closing: true
    reconnect_time: 3.0
    debug_logging: false
    load_map: false
    save_map: true
    enable_interactive_mode: true  #

    # === General Parameters ===
    use_scan_barycenter: true
    minimum_travel_distance: 0.05
    minimum_travel_heading: 0.05
    scan_buffer_size: 50               # เพิ่ม buffer
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.5
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # === Correlation Parameters ===
    correlation_search_space_dimension: 0.3
    correlation_search_space_resolution: 0.015
    correlation_search_space_smear_deviation: 0.1

    # === Loop Closure ===
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.05

    # === Scan Matcher ===
    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.0
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true

